alert("With our Message");
window.confirm("test");
window.prompt("write your name");
let confirmm = confirm("Want to delete? press okay");
console.log(confirmm);
confirmm = confirm("Want to delete? press cancel");
console.log(confirmm);
let num1 = prompt("Write a number");
console.log(num1);
let num2 = prompt("write other number");
console.log(num2);
console.log(num1 + num2);
console.log(typeof num1);
console.log(typeof num2);
num1 = Number(num1);
num2 = Number(num2);
alert(`sum of this count is: ${num1 + num2}`);
console.log(typeof num1);
console.log(typeof num2);
